"""저장소 계층.

- DATABASE_URL 환경변수가 있으면 PostgreSQL(Supabase)
- 없으면 SQLite (로컬 개발·테스트)

모든 DB 접근은 이 모듈을 통해서만 이루어진다. 두 백엔드는 SQL 방언 차이가 작아
플레이스홀더(? → %s)와 DDL·토글 표현식만 분기한다.
"""
import os
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

_initialized = False


# ---------------------------------------------------------------- 백엔드 판별
def get_database_url() -> str | None:
    return os.environ.get("DATABASE_URL") or None


def is_postgres() -> bool:
    return get_database_url() is not None


def _default_db_path() -> str:
    # Vercel 서버리스 환경은 /tmp 만 쓰기 가능
    if os.environ.get("VERCEL"):
        return "/tmp/todo.db"
    return os.path.join(BASE_DIR, "todo.db")


def get_db_path() -> str:
    return os.environ.get("TODO_DB_PATH") or _default_db_path()


def backend_name() -> str:
    return "postgresql" if is_postgres() else "sqlite"


# ---------------------------------------------------------------- 연결
@contextmanager
def _connect():
    """커밋 후 반드시 close 한다.

    sqlite3 의 기본 컨텍스트 매니저는 커밋/롤백만 하고 연결을 닫지 않아
    Windows 에서 파일 잠금이 남고, 서버리스에서는 연결이 누수된다.
    """
    if is_postgres():
        import psycopg
        from psycopg.rows import dict_row

        # Supabase 트랜잭션 풀러(6543)는 서버측 prepared statement 를 지원하지 않으므로 비활성화
        conn = psycopg.connect(get_database_url(), row_factory=dict_row, prepare_threshold=None)
    else:
        conn = sqlite3.connect(get_db_path())
        conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _sql(query: str) -> str:
    """플레이스홀더 방언 변환. SQL 문자열 안에 리터럴 '?' 는 쓰지 않는다."""
    return query.replace("?", "%s") if is_postgres() else query


def init_db() -> None:
    global _initialized
    if _initialized:
        return
    if is_postgres():
        ddl = """
            CREATE TABLE IF NOT EXISTS todos (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title      TEXT        NOT NULL,
                done       BOOLEAN     NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """
    else:
        ddl = """
            CREATE TABLE IF NOT EXISTS todos (
                id         INTEGER PRIMARY KEY AUTOINCREMENT,
                title      TEXT    NOT NULL,
                done       INTEGER NOT NULL DEFAULT 0,
                created_at TEXT    NOT NULL
            )
        """
    with _connect() as conn:
        conn.execute(ddl)
    _initialized = True


def reset_init_flag() -> None:
    """테스트에서 DB 경로를 바꿀 때 사용."""
    global _initialized
    _initialized = False


# ---------------------------------------------------------------- 조회
def _row_to_dict(row) -> dict:
    created = row["created_at"]
    if isinstance(created, datetime):
        created = created.isoformat(timespec="seconds")
    return {
        "id": row["id"],
        "title": row["title"],
        "done": bool(row["done"]),
        "created_at": created,
    }


def list_todos(status: str = "all") -> list[dict]:
    """status: all | active | done"""
    where, params = "", ()
    if status == "active":
        where, params = "WHERE done = ?", (False,)
    elif status == "done":
        where, params = "WHERE done = ?", (True,)
    with _connect() as conn:
        rows = conn.execute(
            _sql(f"SELECT * FROM todos {where} ORDER BY done ASC, id DESC"), params
        ).fetchall()
    return [_row_to_dict(r) for r in rows]


def count_todos() -> dict:
    with _connect() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS total, "
            "COALESCE(SUM(CASE WHEN done THEN 1 ELSE 0 END), 0) AS done FROM todos"
        ).fetchone()
    total = int(row["total"] or 0)
    done = int(row["done"] or 0)
    return {"total": total, "done": done, "active": total - done}


def get_todo(todo_id: int) -> dict | None:
    with _connect() as conn:
        row = conn.execute(_sql("SELECT * FROM todos WHERE id = ?"), (todo_id,)).fetchone()
    return _row_to_dict(row) if row else None


# ---------------------------------------------------------------- 변경
def add_todo(title: str) -> dict:
    created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    with _connect() as conn:
        row = conn.execute(
            _sql("INSERT INTO todos (title, done, created_at) VALUES (?, ?, ?) RETURNING id"),
            (title, False, created_at),
        ).fetchone()
        new_id = row["id"]
    return get_todo(new_id)


def update_todo(todo_id: int, title: str | None = None, done: bool | None = None) -> dict | None:
    sets, params = [], []
    if title is not None:
        sets.append("title = ?")
        params.append(title)
    if done is not None:
        sets.append("done = ?")
        params.append(bool(done))
    if not sets:
        return get_todo(todo_id)
    params.append(todo_id)
    with _connect() as conn:
        conn.execute(_sql(f"UPDATE todos SET {', '.join(sets)} WHERE id = ?"), params)
    return get_todo(todo_id)


def toggle_todo(todo_id: int) -> dict | None:
    expr = "NOT done" if is_postgres() else "1 - done"
    with _connect() as conn:
        conn.execute(_sql(f"UPDATE todos SET done = {expr} WHERE id = ?"), (todo_id,))
    return get_todo(todo_id)


def delete_todo(todo_id: int) -> bool:
    with _connect() as conn:
        cur = conn.execute(_sql("DELETE FROM todos WHERE id = ?"), (todo_id,))
        deleted = cur.rowcount
    return deleted > 0


def clear_done() -> int:
    with _connect() as conn:
        cur = conn.execute(_sql("DELETE FROM todos WHERE done = ?"), (True,))
        deleted = cur.rowcount
    return deleted
